SDL: SDL_stdinc.h File Reference
SDL_stdinc.h File Reference
This is a general header that includes C language support.
#include "SDL_config.h"
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdarg.h>
#include <string.h>
#include <strings.h>
#include <inttypes.h>
#include <ctype.h>
#include <math.h>
#include <iconv.h>
#include "begin_code.h"
#include <alloca.h>
#include "close_code.h"
Macros
#define SDL_arraysize(array) (sizeof(array)/sizeof(array[0]))
The number of elements in an array.
#define SDL_TABLESIZE(table) SDL_arraysize(table)
#define SDL_FOURCC(A, B, C, D)
#define SDL_COMPILE_TIME_ASSERT(name, x) typedef int SDL_dummy_ ## name[(x) * 2 - 1]
#define SDL_stack_alloc(type, count) (type*)alloca(sizeof(type)*(count))
#define SDL_stack_free(data)
#define SDL_min(x, y) (((x) < (y)) ? (x) : (y))
#define SDL_max(x, y) (((x) > (y)) ? (x) : (y))
#define SDL_zero(x) SDL_memset(&(x), 0, sizeof((x)))
#define SDL_zerop(x) SDL_memset((x), 0, sizeof(*(x)))
#define SDL_ICONV_ERROR (size_t)-1
#define SDL_ICONV_E2BIG (size_t)-2
#define SDL_ICONV_EILSEQ (size_t)-3
#define SDL_ICONV_EINVAL (size_t)-4
#define SDL_iconv_utf8_locale(S) SDL_iconv_string("", "UTF-8", S, SDL_strlen(S)+1)
#define SDL_iconv_utf8_ucs2(S) (Uint16 *)SDL_iconv_string("UCS-2-INTERNAL", "UTF-8", S, SDL_strlen(S)+1)
#define SDL_iconv_utf8_ucs4(S) (Uint32 *)SDL_iconv_string("UCS-4-INTERNAL", "UTF-8", S, SDL_strlen(S)+1)
Cast operators
Use proper C++ casts when compiled as C++ to be compatible with the option -Wold-style-cast of GCC (and -Werror=old-style-cast in GCC 4.2 and above).
#define SDL_reinterpret_cast(type, expression) ((type)(expression))
#define SDL_static_cast(type, expression) ((type)(expression))
#define SDL_const_cast(type, expression) ((type)(expression))
Typedefs
typedef struct _SDL_iconv_t * SDL_iconv_t
Functions
void * SDL_malloc (size_t size)
void * SDL_calloc (size_t nmemb, size_t size)
void * SDL_realloc (void *mem, size_t size)
void SDL_free (void *mem)
char * SDL_getenv (const char *name)
int SDL_setenv (const char *name, const char *value, int overwrite)
void SDL_qsort (void *base, size_t nmemb, size_t size, int(*compare)(const void *, const void *))
int SDL_abs (int x)
int SDL_isdigit (int x)
int SDL_isspace (int x)
int SDL_toupper (int x)
int SDL_tolower (int x)
void * SDL_memset (void *dst, int c, size_t len)
SDL_FORCE_INLINE void SDL_memset4 (void *dst, Uint32 val, size_t dwords)
void * SDL_memcpy (void *dst, const void *src, size_t len)
SDL_FORCE_INLINE void * SDL_memcpy4 (void *dst, const void *src, size_t dwords)
void * SDL_memmove (void *dst, const void *src, size_t len)
int SDL_memcmp (const void *s1, const void *s2, size_t len)
size_t SDL_wcslen (const wchar_t *wstr)
size_t SDL_wcslcpy (wchar_t *dst, const wchar_t *src, size_t maxlen)
size_t SDL_wcslcat (wchar_t *dst, const wchar_t *src, size_t maxlen)
size_t SDL_strlen (const char *str)
size_t SDL_strlcpy (char *dst, const char *src, size_t maxlen)
size_t SDL_utf8strlcpy (char *dst, const char *src, size_t dst_bytes)
size_t SDL_strlcat (char *dst, const char *src, size_t maxlen)
char * SDL_strdup (const char *str)
char * SDL_strrev (char *str)
char * SDL_strupr (char *str)
char * SDL_strlwr (char *str)
char * SDL_strchr (const char *str, int c)
char * SDL_strrchr (const char *str, int c)
char * SDL_strstr (const char *haystack, const char *needle)
char * SDL_itoa (int value, char *str, int radix)
char * SDL_uitoa (unsigned int value, char *str, int radix)
char * SDL_ltoa (long value, char *str, int radix)
char * SDL_ultoa (unsigned long value, char *str, int radix)
char * SDL_lltoa (Sint64 value, char *str, int radix)
char * SDL_ulltoa (Uint64 value, char *str, int radix)
int SDL_atoi (const char *str)
double SDL_atof (const char *str)
long SDL_strtol (const char *str, char **endp, int base)
unsigned long SDL_strtoul (const char *str, char **endp, int base)
Sint64 SDL_strtoll (const char *str, char **endp, int base)
Uint64 SDL_strtoull (const char *str, char **endp, int base)
double SDL_strtod (const char *str, char **endp)
int SDL_strcmp (const char *str1, const char *str2)
int SDL_strncmp (const char *str1, const char *str2, size_t maxlen)
int SDL_strcasecmp (const char *str1, const char *str2)
int SDL_strncasecmp (const char *str1, const char *str2, size_t len)
int SDL_sscanf (const char *text, const char *fmt,...)
int SDL_vsscanf (const char *text, const char *fmt, va_list ap)
int SDL_snprintf (char *text, size_t maxlen, const char *fmt,...)
int SDL_vsnprintf (char *text, size_t maxlen, const char *fmt, va_list ap)
double SDL_acos (double x)
double SDL_asin (double x)
double SDL_atan (double x)
double SDL_atan2 (double x, double y)
double SDL_ceil (double x)
double SDL_copysign (double x, double y)
double SDL_cos (double x)
float SDL_cosf (float x)
double SDL_fabs (double x)
double SDL_floor (double x)
double SDL_log (double x)
double SDL_pow (double x, double y)
double SDL_scalbn (double x, int n)
double SDL_sin (double x)
float SDL_sinf (float x)
double SDL_sqrt (double x)
SDL_iconv_t SDL_iconv_open (const char *tocode, const char *fromcode)
int SDL_iconv_close (SDL_iconv_t cd)
size_t SDL_iconv (SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft)
char * SDL_iconv_string (const char *tocode, const char *fromcode, const char *inbuf, size_t inbytesleft)
This function converts a string between encodings in one pass, returning a string that must be freed with SDL_free() or NULL on error.
Basic data types
enum SDL_bool { SDL_FALSE = 0, SDL_TRUE = 1 }
typedef int8_t Sint8
A signed 8-bit integer type.
typedef uint8_t Uint8
An unsigned 8-bit integer type.
typedef int16_t Sint16
A signed 16-bit integer type.
typedef uint16_t Uint16
An unsigned 16-bit integer type.
typedef int32_t Sint32
A signed 32-bit integer type.
typedef uint32_t Uint32
An unsigned 32-bit integer type.
typedef int64_t Sint64
A signed 64-bit integer type.
typedef uint64_t Uint64
An unsigned 64-bit integer type.
Detailed Description
This is a general header that includes C language support.
Macro Definition Documentation
#define SDL_arraysize (array) (sizeof(array)/sizeof(array[0]))
The number of elements in an array.
#define SDL_TABLESIZE (table) SDL_arraysize(table)
#define SDL_reinterpret_cast (type, expression) ((type)(expression))
#define SDL_static_cast (type, expression) ((type)(expression))
Referenced by SDL_memset4(), SDL_Swap16(), SDL_Swap32(), and SDL_Swap64().
#define SDL_const_cast (type, expression) ((type)(expression))
#define SDL_FOURCC (A, B, C, D)
Value:
((SDL_static_cast(Uint32, SDL_static_cast(Uint8, (A))) << 0) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (B))) << 8) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (C))) << 16) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (D))) << 24))
#define SDL_COMPILE_TIME_ASSERT (name, x) typedef int SDL_dummy_ ## name[(x) * 2 - 1]
#define SDL_stack_alloc (type, count) (type*)alloca(sizeof(type)*(count))
#define SDL_stack_free (data)
#define SDL_min (x, y) (((x) < (y)) ? (x) : (y))
#define SDL_max (x, y) (((x) > (y)) ? (x) : (y))
#define SDL_zero (x) SDL_memset(&(x), 0, sizeof((x)))
#define SDL_zerop (x) SDL_memset((x), 0, sizeof(*(x)))
#define SDL_ICONV_ERROR (size_t)-1
#define SDL_ICONV_E2BIG (size_t)-2
#define SDL_ICONV_EILSEQ (size_t)-3
#define SDL_ICONV_EINVAL (size_t)-4
#define SDL_iconv_utf8_locale (S) SDL_iconv_string("", "UTF-8", S, SDL_strlen(S)+1)
#define SDL_iconv_utf8_ucs2 (S) (Uint16 *)SDL_iconv_string("UCS-2-INTERNAL", "UTF-8", S, SDL_strlen(S)+1)
#define SDL_iconv_utf8_ucs4 (S) (Uint32 *)SDL_iconv_string("UCS-4-INTERNAL", "UTF-8", S, SDL_strlen(S)+1)
Typedef Documentation
typedef int8_t Sint8
A signed 8-bit integer type.
typedef uint8_t Uint8
An unsigned 8-bit integer type.
typedef int16_t Sint16
A signed 16-bit integer type.
typedef uint16_t Uint16
An unsigned 16-bit integer type.
typedef int32_t Sint32
A signed 32-bit integer type.
typedef uint32_t Uint32
An unsigned 32-bit integer type.
typedef int64_t Sint64
A signed 64-bit integer type.
typedef uint64_t Uint64
An unsigned 64-bit integer type.
typedef struct _SDL_iconv_t* SDL_iconv_t
Enumeration Type Documentation
enum SDL_bool
Enumerator
SDL_FALSE
SDL_TRUE
Function Documentation
void* SDL_malloc (size_t size)
void* SDL_calloc (size_t nmemb, size_t size)
void* SDL_realloc (void * mem, size_t size)
void SDL_free (void * mem)
char* SDL_getenv (const char * name)
int SDL_setenv (const char * name, const char * value, int overwrite)
void SDL_qsort (void * base, size_t nmemb, size_t size, int(*)(const void *, const void *) compare)
int SDL_abs (int x)
int SDL_isdigit (int x)
int SDL_isspace (int x)
int SDL_toupper (int x)
int SDL_tolower (int x)
void* SDL_memset (void * dst, int c, size_t len)
SDL_FORCE_INLINE void SDL_memset4 (void * dst, Uint32 val, size_t dwords)
References DECLSPEC, SDL_memcpy(), SDL_static_cast, and SDLCALL.
void* SDL_memcpy (void * dst, const void * src, size_t len)
Referenced by SDL_memcpy4(), and SDL_memset4().
SDL_FORCE_INLINE void* SDL_memcpy4 (void * dst, const void * src, size_t dwords)
References DECLSPEC, SDL_acos(), SDL_asin(), SDL_atan(), SDL_atan2(), SDL_atof(), SDL_atoi(), SDL_ceil(), SDL_copysign(), SDL_cos(), SDL_cosf(), SDL_fabs(), SDL_floor(), SDL_itoa(), SDL_lltoa(), SDL_log(), SDL_ltoa(), SDL_memcmp(), SDL_memcpy(), SDL_memmove(), SDL_pow(), SDL_scalbn(), SDL_sin(), SDL_sinf(), SDL_snprintf(), SDL_sqrt(), SDL_sscanf(), SDL_strcasecmp(), SDL_strchr(), SDL_strcmp(), SDL_strdup(), SDL_strlcat(), SDL_strlcpy(), SDL_strlen(), SDL_strlwr(), SDL_strncasecmp(), SDL_strncmp(), SDL_strrchr(), SDL_strrev(), SDL_strstr(), SDL_strtod(), SDL_strtol(), SDL_strtoll(), SDL_strtoul(), SDL_strtoull(), SDL_strupr(), SDL_uitoa(), SDL_ulltoa(), SDL_ultoa(), SDL_utf8strlcpy(), SDL_vsnprintf(), SDL_vsscanf(), SDL_wcslcat(), SDL_wcslcpy(), SDL_wcslen(), and SDLCALL.
void* SDL_memmove (void * dst, const void * src, size_t len)
Referenced by SDL_memcpy4().
int SDL_memcmp (const void * s1, const void * s2, size_t len)
Referenced by SDL_memcpy4().
size_t SDL_wcslen (const wchar_t * wstr)
Referenced by SDL_memcpy4().
size_t SDL_wcslcpy (wchar_t * dst, const wchar_t * src, size_t maxlen)
Referenced by SDL_memcpy4().
size_t SDL_wcslcat (wchar_t * dst, const wchar_t * src, size_t maxlen)
Referenced by SDL_memcpy4().
size_t SDL_strlen (const char * str)
Referenced by SDL_memcpy4().
size_t SDL_strlcpy (char * dst, const char * src, size_t maxlen)
Referenced by SDL_memcpy4().
size_t SDL_utf8strlcpy (char * dst, const char * src, size_t dst_bytes)
Referenced by SDL_memcpy4().
size_t SDL_strlcat (char * dst, const char * src, size_t maxlen)
Referenced by SDL_memcpy4().
char* SDL_strdup (const char * str)
Referenced by SDL_memcpy4().
char* SDL_strrev (char * str)
Referenced by SDL_memcpy4().
char* SDL_strupr (char * str)
Referenced by SDL_memcpy4().
char* SDL_strlwr (char * str)
Referenced by SDL_memcpy4().
char* SDL_strchr (const char * str, int c)
Referenced by SDL_memcpy4().
char* SDL_strrchr (const char * str, int c)
Referenced by SDL_memcpy4().
char* SDL_strstr (const char * haystack, const char * needle)
Referenced by SDL_memcpy4().
char* SDL_itoa (int value, char * str, int radix)
Referenced by SDL_memcpy4().
char* SDL_uitoa (unsigned int value, char * str, int radix)
Referenced by SDL_memcpy4().
char* SDL_ltoa (long value, char * str, int radix)
Referenced by SDL_memcpy4().
char* SDL_ultoa (unsigned long value, char * str, int radix)
Referenced by SDL_memcpy4().
char* SDL_lltoa (Sint64 value, char * str, int radix)
Referenced by SDL_memcpy4().
char* SDL_ulltoa (Uint64 value, char * str, int radix)
Referenced by SDL_memcpy4().
int SDL_atoi (const char * str)
Referenced by SDL_memcpy4().
double SDL_atof (const char * str)
Referenced by SDL_memcpy4().
long SDL_strtol (const char * str, char ** endp, int base)
Referenced by SDL_memcpy4().
unsigned long SDL_strtoul (const char * str, char ** endp, int base)
Referenced by SDL_memcpy4().
Sint64 SDL_strtoll (const char * str, char ** endp, int base)
Referenced by SDL_memcpy4().
Uint64 SDL_strtoull (const char * str, char ** endp, int base)
Referenced by SDL_memcpy4().
double SDL_strtod (const char * str, char ** endp)
Referenced by SDL_memcpy4().
int SDL_strcmp (const char * str1, const char * str2)
Referenced by SDL_memcpy4().
int SDL_strncmp (const char * str1, const char * str2, size_t maxlen)
Referenced by SDL_memcpy4().
int SDL_strcasecmp (const char * str1, const char * str2)
Referenced by SDL_memcpy4().
int SDL_strncasecmp (const char * str1, const char * str2, size_t len)
Referenced by SDL_memcpy4().
int SDL_sscanf (const char * text, const char * fmt, ...)
Referenced by SDL_memcpy4().
int SDL_vsscanf (const char * text, const char * fmt, va_list ap)
Referenced by SDL_memcpy4().
int SDL_snprintf (char * text, size_t maxlen, const char * fmt, ...)
Referenced by SDL_memcpy4().
int SDL_vsnprintf (char * text, size_t maxlen, const char * fmt, va_list ap)
Referenced by SDL_memcpy4().
double SDL_acos (double x)
Referenced by SDL_memcpy4().
double SDL_asin (double x)
Referenced by SDL_memcpy4().
double SDL_atan (double x)
Referenced by SDL_memcpy4().
double SDL_atan2 (double x, double y)
Referenced by SDL_memcpy4().
double SDL_ceil (double x)
Referenced by SDL_memcpy4().
double SDL_copysign (double x, double y)
Referenced by SDL_memcpy4().
double SDL_cos (double x)
Referenced by SDL_memcpy4().
float SDL_cosf (float x)
Referenced by SDL_memcpy4().
double SDL_fabs (double x)
Referenced by SDL_memcpy4().
double SDL_floor (double x)
Referenced by SDL_memcpy4().
double SDL_log (double x)
Referenced by SDL_memcpy4().
double SDL_pow (double x, double y)
Referenced by SDL_memcpy4().
double SDL_scalbn (double x, int n)
Referenced by SDL_memcpy4().
double SDL_sin (double x)
Referenced by SDL_memcpy4().
float SDL_sinf (float x)
Referenced by SDL_memcpy4().
double SDL_sqrt (double x)
Referenced by SDL_memcpy4().
SDL_iconv_t SDL_iconv_open (const char * tocode, const char * fromcode)
int SDL_iconv_close (SDL_iconv_t cd)
size_t SDL_iconv (SDL_iconv_t cd, const char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft)
char* SDL_iconv_string (const char * tocode, const char * fromcode, const char * inbuf, size_t inbytesleft)
This function converts a string between encodings in one pass, returning a string that must be freed with SDL_free() or NULL on error.